title: "Westside Pet Care"
description: "A blog about caring for your pets"
url: "https://westsidepetcare.github.io"
baseurl: "/"
theme: jekyll-theme-cayman  # You can change the theme if you prefer another one
